### PR TITLE
That way you can let through the original exception (such as Mybatis'…

### PR DESCRIPTION
**Pull request by mazerty**
… PersistenceException) instead of having to deal with an ugly UndeclaredThrowableException

### CODE REVIEW

**Comment by mazerty** [comment]
It seems Travis can't build because of the version of mybatis-parent, I can set it to "25" if need be.

**Comment by emacarron** [comment]
Hi @mazerty yes please. Change it before we merge the PR.

**Comment by mazerty** [comment]
done ! all good !

**Comment by emacarron** [comment]
Thank you!

**Pull request merged**
